### ISSUE TITLE
Overlapping text and buttons.

### ISSUE THREAD

**Issue by Ceddix** [arm32x/command-block-ide#1]
Hi! I noticed that when you open a larger command block chain, the **text at the end of the screen is above the buttons**, this looks a bit weird :D

Here is a picture so you can see what I mean:
![Example](https://craft-together.de/~ceddix/uploads/javaw_48ZSHOVGvB.png)
![Zoom](https://craft-together.de/~ceddix/uploads/javaw_YfCAlgesQj.png)

**Version:** command-block-ide-0.1.1

_Otherwise thanks for the great mod, left you another suggestion on CurseForge and a feedback would be great :D_
_(And is there any information about a possible update to 1.17?)_
~Ceddix

**Comment by arm32x** [comment]
I’ve just committed the fix for this, and it will make it into the next release.

I’m working on 1.17 support now, and that should be ready fairly soon.
