### ISSUE TITLE
Update Minecraft version tags for Modrinth and CurseForge

### ISSUE THREAD

**Issue by ghost** [arm32x/command-block-ide#15]
Add the tag for Minecraft version 1.19.2 on [Modrinth](https://modrinth.com/mod/command-block-ide/version/0.3.3) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/command-block-ide/files/4008859). The 0.3.3 mod version works perfectly fine in Minecraft 1.19.2, as I tested.

**Comment by osfanbuff63** [comment]
It's already there.

**Comment by arm32x** [comment]
Done.

I didn't mark it as 1.19.2 when uploading since I only tested it on 1.19.1, but since you've confirmed it works I've marked them as 1.19.2 as well.

@osfanbuff63 I only just added it; you just happened to comment between when I updated it and when I posted this comment.

**Comment by osfanbuff63** [comment]
oh ok lol
