### ISSUE TITLE
Commands aren't shown correctly in the editor

### ISSUE THREAD

**Issue by osfanbuff63** [arm32x/command-block-ide#19]
Commands don't appear to show up in the editor correctly - instead, they just show up grayed out:
![image](https://user-images.githubusercontent.com/91388253/234116157-e4535bd4-5130-437c-b7e6-7b22a474367f.png)

If you notice in the left corner (where chat is) the output of the `/data get` command shows up.
![image](https://user-images.githubusercontent.com/91388253/234116255-31146373-6798-42bc-8e41-c71ee7b06b14.png)

**Steps to reproduce:**
1. Open any line of command blocks that has more than one command block in it
2. Notice how the other command block lines are grayed out, and the output of the `/data get` command is displayed in chat.

**Comment by arm32x** [comment]
I can't reproduce this in my development environment, so I need some additional information before I can fix the issue.

Does this occur in a singleplayer or multiplayer world? If you are on a multiplayer server, please also specify what specific server software is being used (Vanilla, Paper, Spigot, etc.). A good way to find this is the *server brand*, which can be found in the <kbd>F3</kbd> menu like so:

![Server brand in F3 menu](https://user-images.githubusercontent.com/15364665/197360044-d67db50e-b56f-4214-a781-25f40537c01e.png)

**Comment by osfanbuff63** [comment]
Doesn't seem to happen in singleplayer, the multiplayer server I tested and took those screenshots on was using Paper. Notably, the server has ViaVersion, which *could* cause a problem somehow? (I'm connecting to the 1.19.3 server on a 1.19.4 client)

**Comment by GoldEmberMage** [comment]
I've had this same problem on a single-player world that I upgraded from 1.19.3, could upgrading from an older version be causing this issue? The mod works as intended when I created a new world.

**Comment by arm32x** [comment]
I was able to reproduce this on a Paper server with ViaVersion, but I wasn't able to reproduce this after upgrading a world in singleplayer. @GoldEmberMage, if this still occurs on the latest version of the mod (0.4.1), please open a new issue.
