### ISSUE TITLE
[bug][performace improvement] Bad performance on underpowered machines

### ISSUE THREAD

**Issue by ghost** [arm32x/command-block-ide#20]
When editor gui loads commands that have many new lines it becomes significantly less responsive - keyboard and mouse input (mostly noticeable by moving with arrow keys, or mouse) is processed after quite large delay, which gives bad editing experience.

The issue affects gui even when the edited chain only contains one command block.

I suspect that each textbox interaction may cause the command string to be rebuild internally, which could happen to be expensive process, although I have not yet profiled that (currently setting up the java and scala, when I will be done with that, I will try to provide some metrics)

Version used: `0.4.1` from Modrinth
Fabric loader: `0.14.19`
Minecraft verison: `1.19.4`

**Comment by Popa-42** [comment]
I've got the same problem. It seems like the FPS of the whole game drop significantly whenever you open the GUI of a command block containing many newlines, it is not just a delayed keyboard input.
(I'm using the mod version `0.4.3` from Modrinth on Quilt Loader `0.20.2` on Minecraft `1.20.1`)

**Comment by arm32x** [comment]
This should be fixed by commits 293d533e87b339249e69851f105463c8d57534f3 and 4ca0a1eed1c529b09ba05992fe9c68ed4c2111b1.
