### ISSUE TITLE
game crashes when selecting an empty line

### ISSUE THREAD

**Issue by SubwaySurfers69** [arm32x/command-block-ide#23]
my game crashes if I open a new command block, press enter to add a new line, press ctrl + a to select all
I made sure I had no other mods and I can send logs if it helps
not very important but it's a bug so I may as well report it

**Comment by SubwaySurfers69** [comment]
how do you label this as a bug?

**Comment by SubwaySurfers69** [comment]
I also instantly get kicked when opening a chain of commands on my paper server which makes this mod unusable

**Comment by arm32x** [comment]
> how do you label this as a bug?

You don't; you need edit permissions for this repository to add labels. I just add them myself later when I see the issue.

> I also instantly get kicked when opening a chain of commands on my paper server which makes this mod unusable

Please open a separate issue for this. It would also help if you posted logs in your other issue so I can see what the exact error is.
