### ISSUE TITLE
[suggestion] NBT Autocomplete integration

### ISSUE THREAD

**Issue by histefanhere** [arm32x/command-block-ide#25]
Hello! Amazing mod, and exactly what I was missing from my command development for years now. I had previously been trying out [Better Command Block UI](https://modrinth.com/mod/bettercommandblockui) by @Tectato but I consider this easier coming from a programming standpoint.

I was wondering if it was possible to make this mod compatible with [NBT Autocomplete](https://modrinth.com/mod/nbt-autocomplete) by @mt1006 which would mean less work on your side to make autocompletion a thing and a considerable better experience for players. I mentioned Better Command Block UI before because it already _does_ support it, so it should be possible in some way.

**Comment by osfanbuff63** [comment]
NBT autocomplete appears to already work with this mod, at least from my testing.

**Comment by histefanhere** [comment]
You're right! Not sure why it wasn't working back when I tried it. Now just for the mod to be updated to 1.20.2...
