### ISSUE TITLE
Question: Is this mod client-only?

### ISSUE THREAD

**Issue by pavog** [arm32x/command-block-ide#27]
Hi, I just wanted to know if this mod is a client-only mod?
I mean from the description it seems like it is client-only.
But on the [modrinth page](https://modrinth.com/mod/command-block-ide) it says `server side: optional`.
Now I wonder why this mod can be installed on a server when it is client-only?

**Comment by arm32x** [comment]
The mod will work when installed only on the client. Installing the mod on the server adds extra features like datapack support, but is entirely optional.
