### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by MisileLab** [arm32x/command-block-ide#35]
I'm currently making 1.20.2 pr but i have no time and no experience modding so can you port it?

**Comment by arm32x** [comment]
I actually started a port a while ago (ac6223d) and forgot to push it to GitHub. It's not quite ready for a release yet; hopefully I can get that done sometime soon.

**Comment by osfanbuff63** [comment]
Any updates here? Would really like if you could update the mod since it's so useful!

**Comment by arm32x** [comment]
The mod has now been updated to 1.20.4 on both CurseForge and Modrinth. 1.20.2 and 1.20.3 have been skipped.

If you need to use this mod on 1.20.2, you can compile the sources from GitHub; there should be a working version in commit cfa7319d08205981459654226d58b1559da8a6ea.
