### ISSUE TITLE
Text not displaying in 1.20.1

### ISSUE THREAD

**Issue by AutumnAteEverything** [arm32x/command-block-ide#40]
Hello! Love this mod! Unfortunately ran into an issue where the text for each block doesn't show up. Oddly, pasting in commands/autocomplete works, but the text still doesn't show up. This is version 1.20.1 with no other mods installed. 

I tried changing the font, gui scaling, but I can't seem to get the text to appear. I reproduced the issue on two different computers. 
Using Prism Launcher to install the mod from Modrinth. I also tried manually downloading 0.4.3 and 0.4.4 and I got the same result.

For reference, it works perfectly on 1.19.2 - Same installation/configuration process.  
<img width="1512" alt="1 20 1issue" src="https://github.com/arm32x/command-block-ide/assets/26209378/905c1204-0e3b-4c99-a185-3bf293709a27">

**Comment by AutumnAteEverything** [comment]
Small update - the bug seems to only exist on MacOS - Using Sonoma with M1. Tried it on Windows and it works fine. Unfortunately, I need to be on MacOS.

**Comment by arm32x** [comment]
I don't have a Mac to test this, so I can't fix it myself. I'm open to PRs if someone else wants to try, though.

**Comment by GOGDC1707** [comment]
MacOS Sonoma _(the awful buggy mess of an operating system it is)_, **_Intel_** user here, and same problem... so it's nothing to do with the apple silicon chips...

It's a shame as I've only just installed it for the first time and was looking forward to using it... Hope this is fixed soon

**Comment by arm32x** [comment]
Should be fixed by PR GH-43
