### ISSUE TITLE
Suggestion: Expand command field

### ISSUE THREAD

**Issue by Ceddix** [arm32x/command-block-ide#5]
Hi 👋🏻 
It's me again! 😄 

I have a small suggestion and I would be very happy if this is going to be implemented:
Could you maybe add a button to expand a specific command field? Maybe on the side next to the book? 🤔 
That way it would be easier to edit larger commands.

What do you think?

Thanks in advance,
Greetings Ceddix! 👋🏻

**Comment by Ceddix** [comment]
Are there any news for this feature?

**Comment by arm32x** [comment]
Multi-line command support is merged into `mc-release` as of about a week ago. It'll be a bit longer before it makes it into a full release, since there are still some bugs that need to be worked out.
