### ISSUE TITLE
Issue: No TabComplete

### ISSUE THREAD

**Issue by Ceddix** [arm32x/command-block-ide#6]
Hi 👋🏻 

I found a small issue: When you place a commandblock, open its GUI and start typing there's no tabcomplete unless you click the input box.

Thanks in advance,
Greetings Ceddix!

**Comment by arm32x** [comment]
Hi! What version of the mod are you using? This can be seen in [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) if you have it installed.

**Comment by Ceddix** [comment]
![image](https://user-images.githubusercontent.com/49922771/141374704-fcb560fb-64f9-451e-bb5a-9002918d6828.png)

**Comment by arm32x** [comment]
I think I fixed this in cdbac32631b64b2320d4c244ccee41bd26059917 on the `multiline` branch. I'll try to fix this in `master` later.

**Comment by Ceddix** [comment]
Okay, thank you :)

**Comment by Ceddix** [comment]
Is there any chance to reach you on Discord? Would be nice to have another way for questions without needing to open a bug report every time 😅
