### ISSUE TITLE
Command GUI weirdly stretched

### ISSUE THREAD

**Issue by lucreator245** [arm32x/command-block-ide#61]
Hi, my command gui is looking a little odd. Any idea why?
![Screenshot 2024-09-29 103721](https://github.com/user-attachments/assets/61cc3003-922d-4db3-b44e-7d6a4249ef63)

**Comment by arm32x** [comment]
Based on your screenshot, it seems like you are using a resource pack that changes the command block texture. Currently, certain resource packs can break the GUI rendering since Command Block IDE doesn't read animation metadata (`.mcmeta` files).

This is a duplicate of GH-37.
